package util.msg;

public enum TYPE {
	SEND, REQUEST, SET, SUCCESS, FAIL, JOIN, EXIT, SCRIPT,
	CAST, CAST_BROAD, CAST_UNI,
	CHANNEL,
	SEQ,
	NICK,
	FAMILY, FAMILY_PARENT, FAMILY_CHILD,
	IP, 
	MSG,
	END,
}
